/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.LibroLogic;
import Validations.ValidacionesGenerales;
import Logic.BiliotecaLogic;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeric
 */
public class BusquedaBibliotecas extends javax.swing.JFrame {
    LibroLogic L;
    BiliotecaLogic B;
     ValidacionesGenerales valid = new ValidacionesGenerales();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BusquedaBibliotecas.class.getName());

    /**
     * @param sharedLogic Creates new form BusquedaBibliotecas
     */
    public BusquedaBibliotecas(LibroLogic sharedLogic) {
        initComponents();
        this.L = sharedLogic;
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AvisoPane = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        TextoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        TextoBusqueda.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        TextoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TextoBusqueda);
        TextoBusqueda.setBounds(210, 110, 410, 40);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar  Bibliotecas:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 120, 140, 16);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 160, 590, 406);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("B u s q u e d a   d e   B i b l i o t e c a s");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 30, 280, 19);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Buscar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 110, 100, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 510, 100, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Libreria.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1121, 600);

        AvisoPane.setBackground(new java.awt.Color(255, 255, 255));
        AvisoPane.setForeground(new java.awt.Color(0, 0, 0));
        AvisoPane.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jPanel1.add(AvisoPane);
        AvisoPane.setBounds(270, 330, 262, 90);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MainMenu(this.L).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     DefaultTableModel modeloFiltrado =  BiliotecaLogic.Bibliotecas(TextoBusqueda.getText());
        if( BiliotecaLogic.state)
     {
            jTable1.setModel(modeloFiltrado); 
            
            jScrollPane1.setVisible(true);
            this.revalidate();
            this.repaint();
     }else
     {
         jScrollPane1.setVisible(false);
         this.AvisoPane.showMessageDialog(null, "La biblioteca no se ha encontrado!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane AvisoPane;
    private javax.swing.JTextField TextoBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
